//
// ©2023, ANSYS Inc. Unauthorized use, distribution or duplication is prohibited.
//

syntax = "proto3";

package ansys.api.platform.instancemanagement.v1;

import "google/protobuf/empty.proto";

option csharp_namespace = "Ansys.Api.Platform.InstanceManagement.V1";
option go_package = "ansys/api/platform/instancemanagement/v1";

// Manages the creation and deletion of product instances.
// Note: A product instance is the name given to a stateful process starting one or several services.
service ProductInstanceManager {
  // Create a new instance of a product.
  rpc CreateInstance(CreateInstanceRequest) returns (Instance);
  // Remove a running instance of a product.
  rpc DeleteInstance(DeleteInstanceRequest) returns (google.protobuf.Empty);
  // List all running product instances.
  rpc ListInstances(ListInstancesRequest) returns (ListInstancesResponse);
  // Get a running instance of a product.
  // The caller must check what is returned to ensure that
  // the instance is ready before using it.
  // An error is returned if the instance failed
  // to start, crashed, or does not exist.
  rpc GetInstance(GetInstanceRequest) returns (Instance);
  // List all available products that can be started using this product instance manager.
  rpc ListDefinitions(ListDefinitionsRequest) returns (ListDefinitionsResponse);
  // Get a product definition.
  rpc GetDefinition(GetDefinitionRequest) returns (Definition);
}

// Running instance of a product definition
// To list the running instances, use `ListInstances`
message Instance {
  // (Output only) Name of the product instance.
  // The name starts with 'instances/'.
  // For example: instances/workbench-221-12345
  string name = 1;

  // Name of the product definition.
  // For example: definitions/workbench-221
  // Note: To obtain a list of all product definition names, use the
  // `ListDefinitions` method.
  string definition_name = 2;

  // (Output only) Status of the instance.
  // When the status is true, the services can be used.
  bool ready = 3;

  // (Output only) Human-readable message elaborating the status of the instance.
  // Available only if ready is false.
  string status_message = 4;

  // (Output only) Names of the services exposed by this instance.
  // Available only if the instance is ready.
  // The list of keys must match the `available_service_names` of this instance definition.
  // If the instance exposes a main HTTP API, the service must be named "http".
  // If the instance exposes a main gRPC API, the service must be named "grpc".
  map<string, Service> services = 5;
}

// Static definition of a product instance.
// To list all available product definitions, use the `ListDefinitions`
// method.
message Definition {
  // Product definition name.
  // For example: definitions/workbench-221
  string name = 1;

  // Name of the product.
  // For example: workbench
  string product_name = 2;

  // Version of the product.
  // For a product following the unified installation, use
  // the 3-digit format for the version.
  // For example: 221
  string product_version = 3;

  // List of names for the available services that an instance of this definition
  // exposes once it is created.
  // If the instance exposes a main HTTP API, the service must be named "http".
  // If the instance exposes a main gRPC API, the service must be named "grpc".
  repeated string available_service_names = 4;
}

// A service available from a running product instance.
message Service {
  // URI to reach the service.
  // For gRPC, this is a valid URI, following the gRPC name resolution syntax:
  // https://grpc.github.io/grpc/core/md_doc_naming.html
  // For HTTP/REST, this is a valid HTTP or HTTPS URI. It is the base path of the service API.
  string uri = 1;

  // List of headers to pass to the service for each request to the service.
  map<string, string> headers = 2;
}

// Request message for the `CreateInstance` method.
message CreateInstanceRequest {
  // Product instance resource to create.
  // Note: You can call the `ListDefinitions` method to get a list of existing instance
  // definitions.
  Instance instance = 1;
}

// Request message for the `DeleteInstance` method.
message DeleteInstanceRequest {
  // Instance name of the product to delete.
  string name = 1;
}

//
// Request message for the `GetInstance` method.
message GetInstanceRequest {
  // Name of the product instance.
  // For example: instances/example-212-123456879
  string name = 1;
}

// Request message for the `ListInstances` method.
message ListInstancesRequest {
  // Maximum number of product instances to return in the response. If this value
  // is zero, the service selects a default size. A call may return fewer
  // objects than requested. A non-empty `next_page_token` in the response
  // indicates that more data is available.
  int32 page_size = 1;
  // Value returned by the last call to the `ListInstances` method.
  // This value indicates that this is a continuation of a prior `ListInstances` call
  // and that the system should return the next page of data.
  string page_token = 2;
}

// Response message for the `ListInstances` call.
message ListInstancesResponse {
  // List of running product instances.
  repeated Instance instances = 1;
  // If this field is empty, there are no more results in the list.
  // If this field is not empty, it contains the token for retrieving the next page of
  // results. To retrieve the next page of results, pass this token as `page_token`
  // in a new call to the `ListInstances` method.
  string next_page_token = 2;
}

// Request message for the `ListDefinitions` method.
message ListDefinitionsRequest {
  // Maximum number of product definitions to return in the response. If this value
  // is zero, the service selects a default size. A call may return fewer
  // objects than requested. A non-empty `next_page_token` in the response
  // indicates that more data is available.
  int32 page_size = 1;
  // Value returned by the last call to the `ListDefinitions` method.
  // This value indicates that this is a continuation of a prior `ListDefinitions` call
  // and that the system should return the next page of data.
  string page_token = 2;
  // When a product name is specified, only products matching this name are returned.
  // For example: workbench
  string product_name = 3;
  // When a version in the three-digit format is specified, only products matching
  // this version are returned.
  // For example: 211
  string product_version = 4;
}

// Response message for the `ListDefinitions` call.
message ListDefinitionsResponse {
  // List of all products that can be used to start new instances.
  repeated Definition definitions = 1;
  // If this field is empty, there are no more results in the list.
  // If this field is not empty, it contains the token for retrieving the next page of
  // results. To retrieve the next page of results, pass this token as `page_token`
  // in a new call to the `ListDefinitions` method.
  string next_page_token = 2;
}

// Request message for the `GetDefinition` method.
message GetDefinitionRequest {
  // Name of the product definition.
  // For example: definitions/example-212
  // Note: You can call the `ListDefinitions` method to get a list of existing product definitions.
  string name = 1;
}
