name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'
  LIBRARY_NAME: "ansys-api-platform-instancemanagement"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/code-style@v9

  build-library:
    name: "Build library"
    needs: code-style
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/build-library@v9
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  release:
    name: "Release"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: build-library
    runs-on: ubuntu-latest
    steps:

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Download source and wheel distribution"
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: "Display structure of downloaded files"
        run: ls -R dist

      - name: "Release to public PyPI"
        run: |
          python -m pip install twine
          twine upload --skip-existing dist/**/*.whl
          twine upload --skip-existing dist/**/*.tar.gz
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: "Release to GitHub"
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/**/*.whl
            dist/**/*.tar.gz
